services:
  - type: web
    name: invoice-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: LLM_MODEL
        value: gemini-1.5-flash
      - key: LLM_TEMPERATURE
        value: 0.1
      - key: LOG_LEVEL
        value: INFO
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
